name: GitHub Package Registry

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build the image and push it to GitHub Package Registry
        run: |
          # Strip git ref prefix from version
          ref=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Convert from Git ref to image version i.e. strip the 'v'
          if [ "$ref" == "master" ]
          then
            version=latest
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]
          then
            version=$(echo $ref | sed -e 's/^v//')
          else
            version=${version:-$ref}
          fi

          registry=docker.pkg.github.com
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          make image REGISTRY="$registry/${{ github.repository }}" VERSION=$version
          docker logout
